-- ============================================================================
-- SIGHTING SAMPLE DATA
-- SnowGhostBreakers Application
-- Insert 50+ ghost sightings with various locations and evidence details
-- ============================================================================

USE DATABASE GHOST_DETECTION;
USE SCHEMA APP;

-- Clear existing data (optional - comment out for production)
-- TRUNCATE TABLE SIGHTINGS;

INSERT INTO SIGHTINGS (
    SIGHTING_ID,
    GHOST_ID,
    SIGHTING_DATE,
    LOCATION_NAME,
    LATITUDE,
    LONGITUDE,
    COUNTRY,
    REGION,
    EMF_READING,
    TEMPERATURE_CELSIUS,
    TEMPERATURE_ANOMALY_CELSIUS,
    PARANORMAL_ACTIVITY_LEVEL,
    WITNESS_COUNT,
    PRIMARY_WITNESS_NAME,
    WITNESS_CREDIBILITY_SCORE,
    DESCRIPTION,
    WEATHER_CONDITIONS,
    MOON_PHASE,
    CREATED_AT
)
VALUES
-- ============================================================================
-- THE GREY LADY SIGHTINGS (GHOST-001)
-- ============================================================================
(
    'SIGHT-001',
    'GHOST-001',
    '2024-01-15 02:30:00',
    'Willowmere Manor - East Wing',
    53.9590,
    -1.0815,
    'United Kingdom',
    'Yorkshire',
    4.2,
    12.5,
    -6.5,
    6,
    3,
    'Dr. Sarah Mitchell',
    8.5,
    'Observed translucent female figure gliding through east corridor. Figure paused at window for approximately 30 seconds before dissipating. All three witnesses reported feeling profound sadness.',
    'Foggy, light rain',
    'Waning Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-002',
    'GHOST-001',
    '2024-02-28 01:15:00',
    'Willowmere Manor - Library',
    53.9590,
    -1.0815,
    'United Kingdom',
    'Yorkshire',
    5.8,
    10.2,
    -8.8,
    7,
    1,
    'James O''Connor',
    7.0,
    'Solo investigation captured thermal anomaly in library. Witnessed figure examining books on shelf before turning and acknowledging investigator presence. Made direct eye contact for 3 seconds.',
    'Clear, cold',
    'New Moon',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-003',
    'GHOST-001',
    '2024-06-12 23:45:00',
    'Willowmere Manor - Main Staircase',
    53.9590,
    -1.0815,
    'United Kingdom',
    'Yorkshire',
    3.1,
    14.0,
    -5.0,
    5,
    2,
    'Emily Blackwood',
    9.0,
    'Grey Lady descended main staircase in full manifestation. Dress details clearly visible - Victorian mourning attire with lace collar. Vanished upon reaching bottom step.',
    'Overcast, humid',
    'First Quarter',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- BLOODY MARY SIGHTINGS (GHOST-002)
-- ============================================================================
(
    'SIGHT-004',
    'GHOST-002',
    '2024-03-10 00:00:00',
    'Abandoned Thornwood Academy',
    40.7589,
    -73.9851,
    'United States',
    'New York',
    12.4,
    8.0,
    -15.0,
    9,
    4,
    'Marcus Williams',
    6.5,
    'Group of teenagers attempted summoning in girls bathroom. Mirror cracked spontaneously. One participant received three parallel scratches on forearm. Immediate evacuation required.',
    'Clear, cold',
    'Full Moon',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-005',
    'GHOST-002',
    '2024-07-22 23:30:00',
    'Ravenscroft Hotel Room 237',
    51.5074,
    -0.1278,
    'United Kingdom',
    'London',
    14.7,
    5.5,
    -18.5,
    10,
    1,
    'Isabella Chen',
    8.0,
    'Paranormal researcher attempted controlled summoning with full safety protocols. Manifestation exceeded expectations - figure emerged partially from mirror. Face severely disfigured. Session terminated emergency protocol.',
    'Stormy',
    'Waning Gibbous',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- BELL WITCH SIGHTINGS (GHOST-004)
-- ============================================================================
(
    'SIGHT-006',
    'GHOST-004',
    '2024-04-05 03:00:00',
    'Bell Witch Cave',
    36.5764,
    -87.0103,
    'United States',
    'Tennessee',
    8.9,
    9.0,
    -12.0,
    8,
    6,
    'Robert Bell Jr.',
    9.5,
    'Descendant of original Bell family visited cave on anniversary. Disembodied voice called him by name. Stones thrown from unseen source. EVP captured multiple voices speaking simultaneously.',
    'Clear, warm',
    'Waxing Gibbous',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-007',
    'GHOST-004',
    '2024-08-17 02:15:00',
    'Bell Family Cemetery',
    36.5780,
    -87.0090,
    'United States',
    'Tennessee',
    11.2,
    15.0,
    -10.0,
    9,
    4,
    'Amanda Torres',
    8.0,
    'Investigation team experienced equipment malfunction. All batteries drained simultaneously. Team member slapped by unseen force leaving visible handprint. Retreated after 45 minutes.',
    'Partly cloudy',
    'Third Quarter',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- HAT MAN SIGHTINGS (GHOST-007)
-- ============================================================================
(
    'SIGHT-008',
    'GHOST-007',
    '2024-02-14 04:00:00',
    'Private Residence - Sleepover',
    34.0522,
    -118.2437,
    'United States',
    'California',
    6.7,
    18.0,
    -4.0,
    7,
    1,
    'Derek Thompson',
    7.5,
    'Subject experienced sleep paralysis episode. Reported tall figure in hat standing at bedroom doorway. Unable to move or speak for approximately 3 minutes. Figure vanished when subject regained movement.',
    'Clear',
    'Waxing Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-009',
    'GHOST-007',
    '2024-05-30 03:45:00',
    'St. Augustine Lighthouse',
    29.8856,
    -81.2887,
    'United States',
    'Florida',
    5.4,
    22.0,
    -3.0,
    6,
    2,
    'Christine Mueller',
    8.5,
    'Two lighthouse keepers reported identical figure on separate floors simultaneously. Both described wide-brimmed hat and long coat. Security cameras showed static during event timeframe.',
    'Humid, light fog',
    'Full Moon',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-010',
    'GHOST-007',
    '2024-09-03 05:15:00',
    'Hotel & Casino - Room 1408',
    36.1699,
    -115.1398,
    'United States',
    'Nevada',
    7.2,
    16.0,
    -8.0,
    8,
    1,
    'Ricardo Vasquez',
    6.0,
    'Guest reported figure standing over bed upon waking. Described paralyzing fear and inability to scream. Figure appeared to absorb light around it. Lasted approximately 90 seconds.',
    'Clear, dry',
    'New Moon',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- HEADLESS HORSEMAN SIGHTINGS (GHOST-013)
-- ============================================================================
(
    'SIGHT-011',
    'GHOST-013',
    '2024-10-28 00:30:00',
    'Old Dutch Church Road',
    41.0859,
    -73.8612,
    'United States',
    'New York',
    9.8,
    4.0,
    -14.0,
    9,
    7,
    'Officer Patricia Moore',
    9.5,
    'Police officer responding to reports observed mounted figure on black horse. No head visible. Figure pursued patrol car for 200 meters before vanishing at bridge. Dashboard camera corrupted.',
    'Foggy, cold',
    'Waning Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-012',
    'GHOST-013',
    '2024-10-31 01:00:00',
    'Sleepy Hollow Cemetery',
    41.0901,
    -73.8580,
    'United States',
    'New York',
    13.5,
    2.0,
    -18.0,
    10,
    15,
    'Dr. William Van Tassel',
    9.0,
    'Halloween night investigation captured multiple photos and videos. Horseman appeared for full 4 minutes. Threw flaming projectile at investigation tent. Three team members received minor burns.',
    'Clear, freezing',
    'Waning Crescent',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- YUKI-ONNA SIGHTINGS (GHOST-018)
-- ============================================================================
(
    'SIGHT-013',
    'GHOST-018',
    '2024-01-20 16:30:00',
    'Mount Fuji - Fifth Station',
    35.3606,
    138.7274,
    'Japan',
    'Honshu',
    2.1,
    -28.0,
    -8.0,
    7,
    2,
    'Takeshi Yamamoto',
    9.0,
    'Two hikers encountered woman in white kimono during sudden blizzard. She beckoned them to follow. Wise hiker recognized Yuki-onna and sought shelter instead. Companion who followed found unconscious but alive.',
    'Blizzard conditions',
    'Third Quarter',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-014',
    'GHOST-018',
    '2024-02-08 19:00:00',
    'Aokigahara Forest Edge',
    35.4719,
    138.6220,
    'Japan',
    'Honshu',
    3.8,
    -22.0,
    -12.0,
    8,
    1,
    'Dr. Kenji Nakamura',
    8.5,
    'Researcher photographing winter forest encountered apparition. Camera froze solid. Woman spoke single word: "Leave." Researcher complied. Camera thawed undamaged with no photos from encounter.',
    'Heavy snow',
    'Full Moon',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- LA LLORONA SIGHTINGS (GHOST-020)
-- ============================================================================
(
    'SIGHT-015',
    'GHOST-020',
    '2024-03-22 21:00:00',
    'Rio Grande Riverbank',
    25.9017,
    -97.4975,
    'United States',
    'Texas',
    4.5,
    18.0,
    -7.0,
    6,
    4,
    'Maria Gonzalez',
    8.0,
    'Family heard weeping while camping near river. Mother in white seen searching among reeds. Children became agitated and pointed at figure adults initially could not see. Immediate departure.',
    'Warm, clear',
    'Waxing Gibbous',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-016',
    'GHOST-020',
    '2024-06-30 23:15:00',
    'Santa Fe River Walk',
    35.6870,
    -105.9378,
    'United States',
    'New Mexico',
    6.2,
    16.0,
    -9.0,
    7,
    2,
    'Carlos Mendez',
    7.5,
    'Couple walking dog heard wailing. Dog refused to continue and whimpered. Witnessed woman in white approaching from river. Dog bolted, owners followed. Figure pursued for 50 meters.',
    'Clear, dry',
    'Waning Gibbous',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-017',
    'GHOST-020',
    '2024-09-15 22:30:00',
    'Lake Xochimilco',
    19.2577,
    -99.0930,
    'Mexico',
    'Mexico City',
    5.8,
    14.0,
    -11.0,
    8,
    8,
    'Rosa Martinez',
    9.0,
    'Tour boat group witnessed figure walking on water surface. Wailing audible over engine noise. Figure reached toward boat before submerging. All passengers reported profound grief sensation.',
    'Partly cloudy',
    'New Moon',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- GETTYSBURG LIGHTS SIGHTINGS (GHOST-009)
-- ============================================================================
(
    'SIGHT-018',
    'GHOST-009',
    '2024-07-01 03:30:00',
    'Little Round Top',
    39.7917,
    -77.2394,
    'United States',
    'Pennsylvania',
    1.2,
    19.0,
    -2.0,
    4,
    12,
    'Dr. Howard Lawrence',
    9.5,
    'Anniversary investigation captured 47 distinct orbs in formation matching Union defensive positions. Orbs moved in coordinated patterns. Audio recording captured distant drum cadence.',
    'Clear, humid',
    'Full Moon',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-019',
    'GHOST-009',
    '2024-07-03 02:00:00',
    'Devils Den',
    39.7889,
    -77.2447,
    'United States',
    'Pennsylvania',
    1.8,
    17.0,
    -4.0,
    5,
    6,
    'Angela Patterson',
    8.5,
    'Battle anniversary brought increased activity. Blue-white orbs emerged from boulder formations. One orb appeared to land on photographer shoulder before dispersing. No adverse effects reported.',
    'Clear, warm',
    'Full Moon',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- SHADOW CRAWLER SIGHTINGS (GHOST-008)
-- ============================================================================
(
    'SIGHT-020',
    'GHOST-008',
    '2024-04-18 01:45:00',
    'Old St. Marys Hospital - Ward B',
    41.8781,
    -87.6298,
    'United States',
    'Illinois',
    7.3,
    11.0,
    -13.0,
    8,
    3,
    'Detective Frank Morrison',
    8.0,
    'Investigation of reported trespassing revealed no human presence. Team observed dark mass crawling across ceiling in defiance of gravity. Moved counter-clockwise around room perimeter. Sulfur smell confirmed.',
    'Overcast',
    'Waning Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-021',
    'GHOST-008',
    '2024-08-05 00:30:00',
    'Old St. Marys Hospital - Morgue',
    41.8781,
    -87.6298,
    'United States',
    'Illinois',
    9.1,
    6.0,
    -19.0,
    9,
    2,
    'Nina Rodriguez',
    7.5,
    'Two investigators cornered by entity in basement morgue. Shadow expanded to fill doorway. Both reported hearing whispered names. Escaped via emergency exit. One investigator required counseling.',
    'Rainy',
    'Third Quarter',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- ZOZO SIGHTINGS (GHOST-016)
-- ============================================================================
(
    'SIGHT-022',
    'GHOST-016',
    '2024-05-13 22:00:00',
    'Private Residence - Basement',
    33.4484,
    -112.0740,
    'United States',
    'Arizona',
    11.5,
    16.0,
    -10.0,
    9,
    4,
    'Kyle Bennett',
    6.0,
    'Ouija session gone wrong. Planchette spelled ZOZO repeatedly then flew across room. Three scratches appeared on two participants arms. Board subsequently burned. Cleansing performed.',
    'Clear, dry',
    'Waxing Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-023',
    'GHOST-016',
    '2024-11-01 23:00:00',
    'Paranormal Investigation Center',
    39.9526,
    -75.1652,
    'United States',
    'Pennsylvania',
    14.9,
    8.0,
    -17.0,
    10,
    6,
    'Dr. Elizabeth Warren',
    9.5,
    'Controlled study of Zozo phenomenon. Entity manifested despite protective measures. Three electronics exploded. One researcher briefly possessed - spoke in unknown language. Session terminated. Full exorcism required.',
    'Stormy',
    'New Moon',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- ENFIELD POLTERGEIST SIGHTINGS (GHOST-006)
-- ============================================================================
(
    'SIGHT-024',
    'GHOST-006',
    '2024-08-31 03:00:00',
    'Enfield House - Recreation',
    51.6522,
    -0.0808,
    'United Kingdom',
    'London',
    6.8,
    12.0,
    -8.0,
    7,
    4,
    'BBC Documentary Crew',
    9.0,
    'Anniversary documentary filming captured residual activity. Knocking sounds in sequence. Small objects moved. EMF spikes corresponded with knocking pattern. Activity minimal compared to 1977 events.',
    'Overcast',
    'Waning Gibbous',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- CAPTAIN MORGAN SIGHTINGS (GHOST-014)
-- ============================================================================
(
    'SIGHT-025',
    'GHOST-014',
    '2024-03-15 04:00:00',
    'SS Atlantic Wreck Site',
    35.2225,
    -75.5353,
    'United States',
    'North Carolina',
    3.2,
    14.0,
    -5.0,
    5,
    8,
    'Captain John Waters',
    9.5,
    'Fishing vessel encountered apparition of uniformed naval officer during approach of tropical storm. Figure pointed emphatically toward shore. Captain changed course. Storm intensified to category 2 within hours.',
    'Deteriorating',
    'First Quarter',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-026',
    'GHOST-014',
    '2024-07-08 02:30:00',
    'Cape Hatteras Waters',
    35.2551,
    -75.5225,
    'United States',
    'North Carolina',
    2.8,
    21.0,
    -3.0,
    4,
    3,
    'Lieutenant Sarah Briggs',
    8.5,
    'Coast Guard patrol encountered translucent figure standing on bow during routine pass. Figure saluted before dissipating. Crew reported sense of comfort rather than fear. Weather remained clear.',
    'Clear, calm',
    'Waxing Gibbous',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- GREEN MAN SIGHTINGS (GHOST-017)
-- ============================================================================
(
    'SIGHT-027',
    'GHOST-017',
    '2024-03-20 06:15:00',
    'Paviland Cave Entrance',
    51.5667,
    -4.2333,
    'United Kingdom',
    'Wales',
    0.8,
    9.0,
    -1.0,
    3,
    2,
    'Professor Rhys Davies',
    9.5,
    'Spring equinox observation. Moss-covered humanoid figure emerged from cave at dawn. Stood in sunlight for approximately 10 minutes. Wildflowers bloomed in footstep pattern. Entity returned to cave.',
    'Clear, mild',
    'First Quarter',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-028',
    'GHOST-017',
    '2024-06-21 05:00:00',
    'Paviland Cave Interior',
    51.5667,
    -4.2333,
    'United Kingdom',
    'Wales',
    1.1,
    11.0,
    -2.0,
    4,
    5,
    'Dr. Owen Lewis',
    9.0,
    'Summer solstice archaeological team witnessed figure composed of vegetation and ancient bone. Entity examined Red Lady burial site before acknowledging team with nod. No hostility. Departed through solid rock.',
    'Clear, sunny',
    'Waxing Gibbous',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- BANSHEE SIGHTINGS (GHOST-019)
-- ============================================================================
(
    'SIGHT-029',
    'GHOST-019',
    '2024-02-03 01:00:00',
    'Dunluce Castle Ruins',
    55.2108,
    -6.5794,
    'United Kingdom',
    'Northern Ireland',
    2.4,
    4.0,
    -6.0,
    6,
    1,
    'Sean MacDonnell',
    9.5,
    'Family descendant heard wailing during visit. Sound unmistakable despite wind. Glimpsed pale figure at cliff edge. Elder family member passed three days later. Family has recorded 47 such incidents since 1584.',
    'Windy, cold',
    'Third Quarter',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- TOWER OF LONDON PRINCES SIGHTINGS (GHOST-011)
-- ============================================================================
(
    'SIGHT-030',
    'GHOST-011',
    '2024-09-03 02:47:00',
    'Bloody Tower Interior',
    51.5081,
    -0.0759,
    'United Kingdom',
    'London',
    1.5,
    13.0,
    -3.0,
    4,
    3,
    'Yeoman Warder Thomas Brooks',
    10.0,
    'Routine night patrol observed two young boys in white nightgowns descending staircase hand in hand. Boys walked to center of room, appeared to embrace, then faded over 47 seconds. Duration matches historical records exactly.',
    'Clear, cool',
    'Waning Crescent',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- DEMON OF BROWNSVILLE ROAD SIGHTINGS (GHOST-015)
-- ============================================================================
(
    'SIGHT-031',
    'GHOST-015',
    '2024-01-08 03:33:00',
    'Brownsville Road House',
    40.4406,
    -79.9959,
    'United States',
    'Pennsylvania',
    9.7,
    4.0,
    -22.0,
    10,
    4,
    'Father Thomas Maloney',
    9.5,
    'Follow-up investigation to confirm containment. Basement temperature dropped 22°C in seconds. Black mass formed in corner. Red luminescent eyes visible. Containment prayers recited. Entity retreated. Containment holding.',
    'Clear, cold',
    'Waning Crescent',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- ADDITIONAL DIVERSE SIGHTINGS
-- ============================================================================
(
    'SIGHT-032',
    'GHOST-003',
    '2024-04-02 23:00:00',
    'Loch Morar South Shore',
    56.9456,
    -5.8500,
    'United Kingdom',
    'Scotland',
    0.9,
    8.0,
    -1.0,
    3,
    5,
    'Ian MacLeod',
    8.5,
    'Campers observed white-robed figure hovering above water during approaching storm. Figure gestured toward shore urgently. Group relocated to higher ground. Flash flood struck original campsite 2 hours later.',
    'Approaching storm',
    'Full Moon',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-033',
    'GHOST-010',
    '2024-05-17 21:30:00',
    'Moss Beach Distillery Bar',
    37.5267,
    -122.5150,
    'United States',
    'California',
    1.4,
    16.0,
    -2.0,
    3,
    12,
    'Bartender Miguel Santos',
    8.0,
    'Regular Friday night. Blue orb appeared during live jazz performance. Orb moved rhythmically with music. Patrons charmed rather than frightened. Orb circled room twice before exiting through window.',
    'Clear, mild',
    'Waxing Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-034',
    'GHOST-012',
    '2024-10-23 03:00:00',
    'Edgehill Battlefield',
    52.1300,
    -1.4700,
    'United Kingdom',
    'Warwickshire',
    1.9,
    6.0,
    -4.0,
    5,
    23,
    'Historical Society Group',
    9.5,
    'Annual anniversary observation. Phantom battle sounds began at 3 AM. Cannon fire, horse hooves, screaming audible. Ghostly cavalry charge witnessed across field. Phenomenon lasted 47 minutes before fading at dawn.',
    'Foggy, cold',
    'Third Quarter',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-035',
    'GHOST-005',
    '2024-06-08 10:00:00',
    'Rosenheim Law Office - Museum',
    47.8561,
    12.1289,
    'Germany',
    'Bavaria',
    4.2,
    20.0,
    -3.0,
    4,
    8,
    'Dr. Hans Weber',
    9.0,
    'Anniversary commemoration at preserved office. Lights flickered on schedule. Phone rang with no caller. Papers lifted from desk. Minimal activity compared to 1967 but confirms residual energy remains.',
    'Clear, warm',
    'Waning Gibbous',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-036',
    'GHOST-004',
    '2024-11-15 02:00:00',
    'Bell Family Property - Field',
    36.5750,
    -87.0110,
    'United States',
    'Tennessee',
    10.5,
    7.0,
    -15.0,
    9,
    3,
    'Paranormal Investigators Inc.',
    8.5,
    'Three-night investigation yielded results on final night. Multiple EVPs captured including clear voice saying "I am here." Investigator hair pulled. Equipment batteries drained three times despite fresh replacements.',
    'Overcast',
    'Waxing Gibbous',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-037',
    'GHOST-007',
    '2024-07-04 04:30:00',
    'Queen Mary Ship - Cabin B340',
    33.7530,
    -118.1925,
    'United States',
    'California',
    8.1,
    14.0,
    -10.0,
    8,
    1,
    'Overnight Guest Jennifer Blake',
    7.0,
    'Guest in notoriously haunted cabin reported sleep paralysis with Hat Man at foot of bed. Unable to move for 4 minutes. Entity appeared to lean closer before departing through closed door. Guest demanded room change.',
    'Marine layer',
    'New Moon',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-038',
    'GHOST-013',
    '2024-10-25 23:45:00',
    'Tarrytown Road',
    41.0762,
    -73.8587,
    'United States',
    'New York',
    7.8,
    8.0,
    -9.0,
    7,
    2,
    'Uber Driver Samuel Price',
    7.5,
    'Rideshare driver and passenger observed mounted figure crossing road. Horse appeared to have flaming hooves. Figure held pumpkin in hand position. Both witness phones lost power during encounter. Dashcam file corrupted.',
    'Clear, cold',
    'Waning Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-039',
    'GHOST-018',
    '2024-12-15 17:00:00',
    'Hakone Mountain Trail',
    35.2326,
    139.0068,
    'Japan',
    'Honshu',
    3.4,
    -15.0,
    -20.0,
    8,
    3,
    'Miyuki Tanaka',
    9.0,
    'Three hikers caught in sudden whiteout. Woman in white appeared offering to guide them. Lead hiker recognized warning signs from folklore. Group refused politely and built snow shelter. Found dead hiker nearby next morning who had followed.',
    'Blizzard',
    'First Quarter',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-040',
    'GHOST-020',
    '2024-08-12 22:00:00',
    'San Antonio River Walk',
    29.4241,
    -98.4936,
    'United States',
    'Texas',
    5.1,
    28.0,
    -4.0,
    6,
    6,
    'Tour Guide Roberto Sanchez',
    8.5,
    'Evening ghost tour group heard weeping near river. Guide recognized La Llorona manifestation. Children on tour became upset simultaneously. Figure seen briefly in water reflection. Tour concluded early.',
    'Hot, humid',
    'Waning Gibbous',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-041',
    'GHOST-002',
    '2024-09-28 00:15:00',
    'Historic Salem Inn',
    42.5195,
    -70.8967,
    'United States',
    'Massachusetts',
    11.8,
    10.0,
    -14.0,
    9,
    3,
    'Ghost Tour Operator Lisa Murray',
    8.0,
    'Unauthorized Bloody Mary session in historic bathroom. Mirror developed frost pattern despite warm room. Figure appeared briefly. One participant fainted. Second received scratch marks spelling letters B and M.',
    'Clear, cool',
    'Waning Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-042',
    'GHOST-008',
    '2024-11-20 01:00:00',
    'Eastern State Penitentiary',
    39.9684,
    -75.1726,
    'United States',
    'Pennsylvania',
    8.5,
    5.0,
    -16.0,
    8,
    4,
    'Night Security Guard William Torres',
    9.0,
    'Security patrol observed dark mass moving along cellblock ceiling. Mass descended walls in unnatural motion. Pursued guard for three corridors before retreating from flashlight beam. Sulfur smell lingered 2 hours.',
    'Clear, cold',
    'Third Quarter',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-043',
    'GHOST-009',
    '2024-05-30 04:00:00',
    'Pickett''s Charge Field',
    39.8139,
    -77.2358,
    'United States',
    'Pennsylvania',
    1.6,
    18.0,
    -3.0,
    4,
    8,
    'Memorial Day Vigil Group',
    9.5,
    'Memorial Day observation witnessed dozens of orbs rising from field. Orbs drifted toward Union positions before dissipating. Several veterans present reported feeling presence of fellow soldiers. Emotional but peaceful.',
    'Clear, warm',
    'Third Quarter',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-044',
    'GHOST-016',
    '2024-04-01 21:30:00',
    'University Dormitory',
    40.1020,
    -88.2272,
    'United States',
    'Illinois',
    12.3,
    17.0,
    -8.0,
    8,
    5,
    'Resident Advisor Michelle Chang',
    7.0,
    'Students using Ouija board contacted entity identifying as Zozo. Activity escalated rapidly. Board caught fire spontaneously. Room filled with sulfur smell. University counseling services notified. Dorm wing blessed.',
    'Rainy',
    'Waxing Gibbous',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-045',
    'GHOST-001',
    '2024-12-24 00:00:00',
    'Willowmere Manor - Chapel',
    53.9590,
    -1.0815,
    'United Kingdom',
    'Yorkshire',
    4.8,
    8.0,
    -10.0,
    6,
    6,
    'Christmas Eve Service Attendees',
    9.0,
    'Midnight mass interrupted by appearance of Grey Lady in chapel doorway. Figure remained for full hymn duration. Several attendees reported hearing woman''s voice join singing. Figure smiled before fading.',
    'Snow, cold',
    'Waning Gibbous',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-046',
    'GHOST-014',
    '2024-09-02 05:00:00',
    'Diamond Shoals',
    35.1528,
    -75.4025,
    'United States',
    'North Carolina',
    2.9,
    24.0,
    -2.0,
    4,
    4,
    'Research Vessel Crew',
    9.5,
    'Oceanographic research vessel encountered apparition during hurricane season survey. 18th century naval officer appeared on deck pointing toward Cape Hatteras. Captain altered course. Hurricane Irene struck original destination hours later.',
    'Deteriorating',
    'Waxing Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-047',
    'GHOST-019',
    '2024-07-18 23:30:00',
    'MacDonnell Family Estate',
    55.2000,
    -6.5000,
    'United Kingdom',
    'Northern Ireland',
    2.1,
    12.0,
    -4.0,
    5,
    2,
    'Caretaker Patrick O''Neill',
    9.5,
    'Caretaker and wife heard wailing from cliff direction. Both felt overwhelming sorrow. Sound continued for 20 minutes. Family matriarch passed away at mainland hospital during same timeframe.',
    'Overcast, windy',
    'First Quarter',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-048',
    'GHOST-017',
    '2024-09-22 06:30:00',
    'Gower Peninsula Woodland',
    51.5700,
    -4.2500,
    'United Kingdom',
    'Wales',
    0.7,
    14.0,
    -1.0,
    3,
    1,
    'Wildlife Photographer Bronwen Hughes',
    8.5,
    'Autumn equinox photography session captured figure emerging from oak grove. Entity appeared composed of leaves, bark, and moss. Made eye contact through camera lens. Pointed at nearby stream. Photographer found rare orchid species there.',
    'Misty, cool',
    'Full Moon',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-049',
    'GHOST-010',
    '2024-10-15 20:00:00',
    'Moss Beach Distillery Patio',
    37.5267,
    -122.5150,
    'United States',
    'California',
    1.2,
    15.0,
    -2.0,
    3,
    18,
    'Wedding Reception Guests',
    8.0,
    'Wedding reception witnessed blue orb appear during first dance. Orb circled couple three times before drifting to ocean. Bride reported feeling presence of deceased grandmother. Phenomenon caught on multiple phones.',
    'Clear, mild',
    'Waning Gibbous',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-050',
    'GHOST-003',
    '2024-11-08 04:00:00',
    'Loch Morar Deep Water',
    56.9500,
    -5.8600,
    'United Kingdom',
    'Scotland',
    0.6,
    6.0,
    -1.0,
    2,
    3,
    'Early Morning Fishermen',
    9.0,
    'Three fishermen observed White Lady walking across water surface toward approaching fog bank. Figure appeared to be herding something away from boat. Fishermen later learned of underwater landslide in area where figure had directed attention.',
    'Pre-dawn fog',
    'New Moon',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-051',
    'GHOST-015',
    '2024-06-06 03:06:00',
    'Brownsville Road Neighborhood',
    40.4400,
    -79.9960,
    'United States',
    'Pennsylvania',
    7.4,
    12.0,
    -14.0,
    7,
    2,
    'Neighbor Dorothy Callahan',
    8.5,
    'Neighbor reported seeing red glowing eyes in window of sealed house. Called authorities. Investigation found no entry but sulfur smell throughout property. Containment rituals refreshed by diocesan representative.',
    'Clear, warm',
    'Waning Crescent',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-052',
    'GHOST-011',
    '2024-04-09 03:00:00',
    'Tower of London Grounds',
    51.5081,
    -0.0760,
    'United Kingdom',
    'London',
    1.3,
    11.0,
    -2.0,
    3,
    1,
    'Night Security K-9 Handler',
    9.5,
    'Guard dog refused to enter Bloody Tower area. Handler observed two small figures in white descending exterior staircase. Figures walked through locked gate. Dog whimpered until figures departed. No alarms triggered.',
    'Partly cloudy',
    'First Quarter',
    CURRENT_TIMESTAMP()
),
(
    'SIGHT-053',
    'GHOST-006',
    '2024-12-01 02:30:00',
    'Enfield Memorial Site',
    51.6520,
    -0.0810,
    'United Kingdom',
    'London',
    5.2,
    9.0,
    -7.0,
    5,
    2,
    'Paranormal Researchers UK',
    8.5,
    'Anniversary investigation detected familiar knocking pattern from 1977 recordings. Furniture vibrated. Voice on audio recorder said "still here" in voice matching Janet Hodgson. Activity subsided after 40 minutes.',
    'Cold, clear',
    'Waxing Gibbous',
    CURRENT_TIMESTAMP()
);

-- Verify insert count and distribution
SELECT 
    COUNTRY,
    COUNT(*) AS SIGHTING_COUNT,
    AVG(PARANORMAL_ACTIVITY_LEVEL) AS AVG_ACTIVITY_LEVEL,
    AVG(EMF_READING) AS AVG_EMF
FROM SIGHTINGS
GROUP BY COUNTRY
ORDER BY SIGHTING_COUNT DESC;

SELECT 
    GHOST_ID,
    COUNT(*) AS SIGHTING_COUNT
FROM SIGHTINGS
GROUP BY GHOST_ID
ORDER BY SIGHTING_COUNT DESC;
