-- ============================================================================
-- EVIDENCE SAMPLE DATA
-- SnowGhostBreakers Application
-- Insert 30+ evidence items with various types and metadata
-- ============================================================================

USE DATABASE GHOST_DETECTION;
USE SCHEMA APP;

-- Clear existing data (optional - comment out for production)
-- TRUNCATE TABLE EVIDENCE;

INSERT INTO EVIDENCE (
    EVIDENCE_ID,
    SIGHTING_ID,
    EVIDENCE_TYPE,
    FILE_PATH,
    FILE_NAME,
    FILE_SIZE_BYTES,
    CAPTURE_DEVICE,
    CAPTURE_TIMESTAMP,
    DURATION_SECONDS,
    DESCRIPTION,
    AUTHENTICITY_SCORE,
    ANALYSIS_STATUS,
    ANALYSIS_NOTES,
    METADATA,
    CREATED_AT
)
VALUES
-- ============================================================================
-- PHOTOGRAPH EVIDENCE
-- ============================================================================
(
    'EVID-001',
    'SIGHT-001',
    'Photograph',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/photos/grey_lady_001.jpg',
    'grey_lady_001.jpg',
    4521984,
    'Sony A7IV Full Frame',
    '2024-01-15 02:31:15',
    NULL,
    'Full-body apparition captured in east corridor. Figure clearly visible as translucent female form. Victorian dress details distinguishable. 30-second exposure with tripod.',
    9.2,
    'Verified',
    'Image analysis confirms no digital manipulation. Light refraction patterns consistent with paranormal manifestation. Metadata verified authentic.',
    '{"iso": 6400, "aperture": "f/2.8", "shutter_speed": "30s", "focal_length": "35mm", "white_balance": "auto", "raw_format": true, "gps_embedded": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-002',
    'SIGHT-004',
    'Photograph',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/photos/bloody_mary_mirror_001.jpg',
    'bloody_mary_mirror_001.jpg',
    3847291,
    'Canon EOS R5',
    '2024-03-10 00:01:42',
    NULL,
    'Mirror crack propagation captured mid-event. Faint face visible in reflection that was not present in room. One of clearest Bloody Mary manifestation photos on record.',
    8.7,
    'Verified',
    'Forensic analysis shows crack pattern inconsistent with impact damage. Face in reflection does not match any person present. No evidence of double exposure.',
    '{"iso": 12800, "aperture": "f/1.8", "shutter_speed": "1/60s", "focal_length": "50mm", "flash": false, "continuous_shooting": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-003',
    'SIGHT-011',
    'Photograph',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/photos/horseman_001.jpg',
    'horseman_001.jpg',
    5892341,
    'Nikon Z9',
    '2024-10-28 00:32:18',
    NULL,
    'Long exposure capture of mounted figure on Old Dutch Church Road. Horse and rider silhouette clearly visible against tree line. No head visible on rider.',
    9.5,
    'Verified',
    'Multiple exposure analysis confirms single continuous capture. No evidence of costume or prop. Horse gait pattern matches historical cavalry training.',
    '{"iso": 8000, "aperture": "f/4", "shutter_speed": "5s", "focal_length": "70mm", "image_stabilization": true, "burst_mode": false}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-004',
    'SIGHT-018',
    'Photograph',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/photos/gettysburg_orbs_001.jpg',
    'gettysburg_orbs_001.jpg',
    6234891,
    'Fujifilm GFX 100S',
    '2024-07-01 03:45:22',
    NULL,
    'Panoramic capture of Little Round Top showing 47 distinct orbs in formation. Blue-white luminescence visible. Orbs positioned along historical defensive line.',
    9.0,
    'Verified',
    'Orb patterns do not match lens flare, dust, or moisture artifacts. Light spectrum analysis shows unusual blue shift. Formation matches 1863 battle maps.',
    '{"iso": 3200, "aperture": "f/5.6", "shutter_speed": "15s", "focal_length": "23mm", "medium_format": true, "panorama_stitched": false}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-005',
    'SIGHT-027',
    'Photograph',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/photos/green_man_001.jpg',
    'green_man_001.jpg',
    4123456,
    'Leica Q2',
    '2024-03-20 06:18:33',
    NULL,
    'Dawn equinox capture of vegetation-covered humanoid figure at cave entrance. Moss, leaves, and bark texture visible. Figure caught mid-step.',
    8.5,
    'Verified',
    'No evidence of costume or practical effects. Vegetation pattern does not match any known species combination. Footprint wildflowers verified blooming.',
    '{"iso": 1600, "aperture": "f/2.8", "shutter_speed": "1/250s", "focal_length": "28mm", "weather_sealed": true, "autofocus_tracking": true}',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- VIDEO EVIDENCE
-- ============================================================================
(
    'EVID-006',
    'SIGHT-002',
    'Video',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/video/grey_lady_library.mp4',
    'grey_lady_library.mp4',
    892341567,
    'RED Komodo 6K',
    '2024-02-28 01:12:00',
    187,
    'Three-minute continuous footage of Grey Lady manifestation in library. Entity examines books, turns, and makes eye contact with camera. Highest quality Grey Lady footage captured.',
    9.8,
    'Verified',
    'Frame-by-frame analysis shows consistent manifestation throughout. No jump cuts or digital manipulation. Audio captured simultaneous temperature drop. Groundbreaking footage.',
    '{"resolution": "6144x3240", "frame_rate": "60fps", "codec": "REDCODE RAW", "color_space": "REDWideGamutRGB", "audio_channels": 4, "timecode_embedded": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-007',
    'SIGHT-012',
    'Video',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/video/horseman_chase.mp4',
    'horseman_chase.mp4',
    1234567890,
    'Blackmagic URSA Mini Pro 12K',
    '2024-10-31 01:02:15',
    243,
    'Four-minute footage of Headless Horseman in full manifestation. Includes horse gallop, pumpkin throw, and pursuit of investigation team. Multiple camera angles synchronized.',
    9.9,
    'Verified',
    'Highest quality paranormal video evidence ever recorded. Frame analysis confirms non-physical nature of entity. Heat signature absent on thermal overlay. Historic documentation.',
    '{"resolution": "12288x6480", "frame_rate": "120fps", "codec": "Blackmagic RAW", "dynamic_range": "13_stops", "multi_cam_sync": true, "drone_footage_included": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-008',
    'SIGHT-020',
    'Video',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/video/shadow_crawler_ward_b.mp4',
    'shadow_crawler_ward_b.mp4',
    567234891,
    'Sony FX6',
    '2024-04-18 01:43:00',
    156,
    'Infrared footage of Shadow Crawler moving across hospital ceiling. Entity moves counter-clockwise in defiance of gravity. Multiple perspective captures.',
    9.1,
    'Verified',
    'Movement pattern analysis shows non-human locomotion. Shadow density blocks infrared completely. Audio captured sulfuric compound signatures.',
    '{"resolution": "4096x2160", "frame_rate": "60fps", "codec": "XAVC-I", "infrared_mode": true, "night_vision": true, "audio_recorder": "separate_sync"}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-009',
    'SIGHT-030',
    'Video',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/video/tower_princes.mp4',
    'tower_princes.mp4',
    234567891,
    'Security CCTV System',
    '2024-09-03 02:47:00',
    47,
    'Security footage capturing Tower Princes manifestation. Two boys in white nightgowns descend staircase hand in hand. Duration precisely 47 seconds matching all historical records.',
    9.7,
    'Verified',
    'Timestamp analysis confirms exact 47-second duration. Children''s clothing matches 15th century historical records. Gait analysis suggests ages 10-12. Remarkable consistency with centuries of reports.',
    '{"resolution": "1920x1080", "frame_rate": "30fps", "codec": "H.264", "camera_id": "BLOODY_TOWER_CAM_03", "night_mode": true, "motion_triggered": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-010',
    'SIGHT-034',
    'Video',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/video/edgehill_phantom_army.mp4',
    'edgehill_phantom_army.mp4',
    2341567890,
    'Multiple Synchronized Cameras',
    '2024-10-23 03:00:00',
    2820,
    'Full 47-minute recording of Phantom Army of Edgehill manifestation. Cavalry charges, cannon fire, infantry movements all visible. Audio captured battle sounds.',
    9.6,
    'Verified',
    'Largest scale paranormal video documentation. Entity count exceeds 500 individual manifestations. Battle tactics match historical English Civil War records. Unprecedented footage.',
    '{"resolution": "8192x4320", "frame_rate": "60fps", "codec": "ProRes 4444", "camera_count": 12, "drone_count": 3, "thermal_overlay": true, "audio_spatial": true}',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- AUDIO EVIDENCE
-- ============================================================================
(
    'EVID-011',
    'SIGHT-006',
    'Audio',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/audio/bell_witch_evp_001.wav',
    'bell_witch_evp_001.wav',
    45678912,
    'Zoom H8 Field Recorder',
    '2024-04-05 03:15:00',
    892,
    'Extended EVP session at Bell Witch Cave. Multiple voice phenomena captured including entity calling investigator by name. Clear words: "Robert Bell... come home..."',
    9.3,
    'Verified',
    'Audio spectrum analysis confirms voice is not from any present person. Frequency patterns match historical Bell Witch recordings from 1970s investigations. Name spoken correctly.',
    '{"sample_rate": "192000", "bit_depth": 32, "channels": 8, "format": "WAV", "noise_reduction": "none_applied", "ambient_db": 28}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-012',
    'SIGHT-015',
    'Audio',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/audio/llorona_wailing.wav',
    'llorona_wailing.wav',
    34567891,
    'Sennheiser MKH 8060',
    '2024-03-22 21:05:00',
    423,
    'Seven-minute recording of La Llorona wailing. Distinct words "Ay, mis hijos" captured multiple times. Sound source moved along riverbank during recording.',
    9.0,
    'Verified',
    'Voice pattern analysis shows non-human harmonic structure. Sound localization tracks movement along 200-meter path. Frequency includes subsonic components affecting emotional state.',
    '{"sample_rate": "96000", "bit_depth": 24, "channels": 2, "format": "WAV", "polar_pattern": "supercardioid", "phantom_power": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-013',
    'SIGHT-029',
    'Audio',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/audio/banshee_wail.wav',
    'banshee_wail.wav',
    28934567,
    'DPA 4006A Omnidirectional',
    '2024-02-03 01:02:00',
    1234,
    'Twenty-minute recording of Banshee wailing at Dunluce Castle. Sound carried over 3 kilometers based on multiple recording positions. Preceded family death by 72 hours.',
    9.5,
    'Verified',
    'Acoustic analysis shows sound properties impossible for human vocal cords. Carried clearly over wind noise without amplification. Correlates with documented family death.',
    '{"sample_rate": "192000", "bit_depth": 32, "channels": 1, "format": "WAV", "multiple_positions": true, "wind_filter": "none_effective"}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-014',
    'SIGHT-024',
    'Audio',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/audio/enfield_knocking.wav',
    'enfield_knocking.wav',
    12345678,
    'Neumann U87',
    '2024-08-31 03:12:00',
    567,
    'Anniversary recording capturing familiar Enfield knocking pattern. Sequence matches 1977 recordings exactly. Voice captured saying "still here" in voice matching Janet Hodgson.',
    9.2,
    'Verified',
    'Knock pattern analysis matches original SPR recordings 100%. Voice comparison with 1977 recordings shows 94% match to Janet Hodgson at age 11. Janet now 58 years old.',
    '{"sample_rate": "96000", "bit_depth": 24, "channels": 2, "format": "WAV", "pattern_match": "confirmed", "voice_analysis": "completed"}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-015',
    'SIGHT-007',
    'Audio',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/audio/bell_witch_multivoice.wav',
    'bell_witch_multivoice.wav',
    67891234,
    'Sound Devices MixPre-10 II',
    '2024-08-17 02:30:00',
    1567,
    'Complex EVP capture with multiple simultaneous voices. Entity demonstrated ability to speak as different people. Warning messages directed at team members by name.',
    9.4,
    'Verified',
    'Voice separation analysis identifies minimum 7 distinct vocal patterns occurring simultaneously. No electronic voice generation detected. Historically consistent behavior.',
    '{"sample_rate": "192000", "bit_depth": 32, "channels": 10, "format": "WAV", "voice_count": 7, "simultaneous_speakers": true}',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- EMF RECORDING EVIDENCE
-- ============================================================================
(
    'EVID-016',
    'SIGHT-005',
    'EMF_Recording',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/emf/bloody_mary_emf_spike.csv',
    'bloody_mary_emf_spike.csv',
    234567,
    'Trifield TF2 EMF Meter',
    '2024-07-22 23:32:00',
    180,
    'Three-minute EMF recording during Bloody Mary manifestation. Readings spiked from 0.2 mG to 14.7 mG at moment of appearance. Pattern shows oscillation during emergence from mirror.',
    9.1,
    'Verified',
    'EMF pattern unique to mirror-based manifestations. Peak correlates precisely with visual observation. Baseline return took 47 seconds post-dissipation.',
    '{"sample_interval_ms": 100, "baseline_mg": 0.2, "peak_mg": 14.7, "frequency_hz": 60, "calibrated": true, "data_points": 1800}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-017',
    'SIGHT-023',
    'EMF_Recording',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/emf/zozo_manifestation.csv',
    'zozo_manifestation.csv',
    456789,
    'K-II EMF Meter Array',
    '2024-11-01 23:15:00',
    600,
    'Ten-minute EMF array recording during Zozo manifestation. All five meters in array registered simultaneously. Readings exceeded measurement capacity at 15+ mG.',
    9.6,
    'Verified',
    'Unprecedented EMF levels across entire investigation space. Pattern shows chaotic fluctuation consistent with demonic classification. Three electronics failed during peak.',
    '{"sample_interval_ms": 50, "meter_count": 5, "baseline_mg": 0.3, "peak_mg": "exceeded_15", "frequency_hz": "variable", "equipment_failures": 3}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-018',
    'SIGHT-031',
    'EMF_Recording',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/emf/brownsville_demon.csv',
    'brownsville_demon.csv',
    345678,
    'Professional EMF Monitoring Station',
    '2024-01-08 03:33:00',
    300,
    'Five-minute recording during containment verification. EMF spiked to 9.7 mG when entity manifested. Readings stabilized after prayers. Confirms containment holding.',
    9.3,
    'Verified',
    'EMF pattern matches 2006 exorcism recordings. Peak correlates with visual confirmation of red eyes. Containment protocols effective based on rapid stabilization.',
    '{"sample_interval_ms": 100, "baseline_mg": 0.5, "peak_mg": 9.7, "containment_verified": true, "ritual_response": "positive"}',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- THERMAL IMAGE EVIDENCE
-- ============================================================================
(
    'EVID-019',
    'SIGHT-013',
    'Thermal_Image',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/thermal/yuki_onna_001.jpg',
    'yuki_onna_001.jpg',
    2345678,
    'FLIR T1020',
    '2024-01-20 16:35:00',
    NULL,
    'Thermal capture of Yuki-onna during blizzard encounter. Figure registers at -45°C against -28°C ambient. Coldest paranormal entity on record.',
    9.4,
    'Verified',
    'Temperature differential of 17°C below ambient unprecedented. Cold signature persisted for full observation period. Matches folklore descriptions of freezing breath.',
    '{"resolution": "1024x768", "temperature_range": "-40C_to_150C", "entity_temp": -45, "ambient_temp": -28, "emissivity": 0.95, "accuracy": "plus_minus_1C"}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-020',
    'SIGHT-039',
    'Thermal_Image',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/thermal/yuki_onna_002.jpg',
    'yuki_onna_002.jpg',
    2567891,
    'FLIR E96',
    '2024-12-15 17:05:00',
    NULL,
    'Thermal image showing Yuki-onna figure approaching hikers. Clear human-shaped cold spot moving through blizzard. Led to discovery of deceased hiker who followed.',
    9.2,
    'Verified',
    'Cold signature formed clear humanoid shape. Movement tracked across 50-meter observation. Correlated with witness accounts of woman in white.',
    '{"resolution": "640x480", "temperature_range": "-20C_to_120C", "entity_temp": -38, "ambient_temp": -15, "tracking_enabled": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-021',
    'SIGHT-008',
    'Thermal_Image',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/thermal/hat_man_doorway.jpg',
    'hat_man_doorway.jpg',
    1987654,
    'Seek Thermal Pro',
    '2024-02-14 04:02:00',
    NULL,
    'Thermal capture of Hat Man in bedroom doorway during sleep paralysis event. Entity appears as complete thermal void - no heat signature whatsoever.',
    8.9,
    'Verified',
    'Absolute thermal void unusual even for paranormal entities. Suggests entity absorbs rather than emits energy. Consistent with shadow figure classification.',
    '{"resolution": "320x240", "temperature_range": "-40C_to_330C", "entity_temp": "void", "ambient_temp": 18, "void_confirmed": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-022',
    'SIGHT-021',
    'Thermal_Image',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/thermal/shadow_crawler_ceiling.jpg',
    'shadow_crawler_ceiling.jpg',
    2123456,
    'FLIR ONE Pro',
    '2024-08-05 00:35:00',
    NULL,
    'Thermal capture of Shadow Crawler on morgue ceiling. Entity displays cold center surrounded by warm corona. Movement creates thermal trail.',
    9.0,
    'Verified',
    'Unique thermal signature for shadow entity. Cold core suggests energy absorption. Warm corona indicates environmental interaction. Trail persisted 30 seconds.',
    '{"resolution": "160x120", "entity_core_temp": -5, "corona_temp": 28, "ambient_temp": 6, "trail_duration_sec": 30}',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- PHYSICAL EVIDENCE
-- ============================================================================
(
    'EVID-023',
    'SIGHT-004',
    'Physical',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/physical/mirror_crack_sample.jpg',
    'mirror_crack_sample.jpg',
    1234567,
    'Evidence Collection Kit',
    '2024-03-10 00:15:00',
    NULL,
    'Mirror glass sample from Bloody Mary summoning. Crack pattern shows internal stress fracture inconsistent with impact. Glass sample retained for laboratory analysis.',
    8.8,
    'Verified',
    'Material analysis shows no impact point. Fracture originated from within glass matrix. No temperature differential to explain thermal stress. Unexplained phenomenon.',
    '{"collection_method": "sterile_forceps", "container": "evidence_bag", "chain_of_custody": true, "lab_submitted": true, "result": "anomalous_fracture_pattern"}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-024',
    'SIGHT-022',
    'Physical',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/physical/zozo_scratches_photo.jpg',
    'zozo_scratches_photo.jpg',
    987654,
    'Medical Documentation Camera',
    '2024-05-13 22:30:00',
    NULL,
    'Photograph of scratches appearing on participant during Zozo session. Three parallel marks appeared without physical contact. Medical examination documented.',
    9.1,
    'Verified',
    'Scratch marks appeared in presence of multiple witnesses. No sharp objects in proximity. Wound pattern consistent with claw marks. Healed within 72 hours.',
    '{"wound_type": "laceration", "count": 3, "depth_mm": 2, "parallel_spacing_mm": 12, "witness_count": 4, "medical_report": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-025',
    'SIGHT-012',
    'Physical',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/physical/pumpkin_residue.jpg',
    'pumpkin_residue.jpg',
    876543,
    'Forensic Evidence Kit',
    '2024-10-31 01:20:00',
    NULL,
    'Burned pumpkin residue from Headless Horseman projectile. Material analysis shows unusual combustion properties. Residue collected from investigation tent.',
    9.4,
    'Verified',
    'Pumpkin matter confirmed by botanical analysis. Combustion temperature exceeded normal burning parameters. No accelerant detected. Burn pattern consistent with supernatural origin.',
    '{"material": "cucurbita_pepo", "combustion_temp_c": 800, "accelerant_detected": false, "sample_weight_g": 45, "analysis": "complete"}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-026',
    'SIGHT-027',
    'Physical',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/physical/wildflower_footprint.jpg',
    'wildflower_footprint.jpg',
    1567890,
    'Botanical Survey Equipment',
    '2024-03-20 07:00:00',
    NULL,
    'Photograph of wildflowers blooming in Green Man footprint pattern. Flowers emerged within hours of sighting. Species includes rare Welsh orchid.',
    8.7,
    'Verified',
    'Botanical survey confirms accelerated growth impossible through natural means. Flower pattern matches observed entity footsteps. Rare species not previously recorded in area.',
    '{"flower_species": ["orchis_mascula", "primula_vulgaris", "viola_riviniana"], "growth_rate": "accelerated", "pattern_match": true, "botanical_report": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-027',
    'SIGHT-031',
    'Physical',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/physical/sulfur_sample.jpg',
    'sulfur_sample.jpg',
    654321,
    'Chemical Analysis Kit',
    '2024-01-08 04:00:00',
    NULL,
    'Air sample containing elevated sulfur compounds from Brownsville Road property. Collected during containment verification. Chemical signature consistent with demonic presence.',
    9.2,
    'Verified',
    'Gas chromatography confirms hydrogen sulfide and sulfur dioxide. Concentration 15x normal ambient levels. No industrial source within 5 kilometers. Pattern matches 2006 exorcism samples.',
    '{"compound": "H2S_SO2_mixture", "concentration_ppm": 45, "collection_method": "air_sampling", "lab_analysis": "gas_chromatography", "source": "unknown"}',
    CURRENT_TIMESTAMP()
),

-- ============================================================================
-- ADDITIONAL DIVERSE EVIDENCE
-- ============================================================================
(
    'EVID-028',
    'SIGHT-017',
    'Video',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/video/llorona_lake.mp4',
    'llorona_lake.mp4',
    456789123,
    'GoPro Hero 11',
    '2024-09-15 22:32:00',
    78,
    'Tour boat footage of La Llorona walking on water surface. Figure reaches toward boat before submerging. Multiple witness phones captured simultaneously.',
    9.3,
    'Verified',
    'Water surface interaction visible. No boat or platform detected under figure. Submersion point showed no displaced water. Multiple angle corroboration.',
    '{"resolution": "5312x2988", "frame_rate": "60fps", "stabilization": "hypersmooth", "water_visibility": "clear", "witness_footage_count": 8}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-029',
    'SIGHT-038',
    'EMF_Recording',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/emf/horseman_road.csv',
    'horseman_road.csv',
    189234,
    'Paranormal EMF Logger',
    '2024-10-25 23:47:00',
    120,
    'EMF recording during Tarrytown Road Horseman sighting. Both witness phones lost power during 7.8 mG spike. Pattern shows movement along road.',
    8.6,
    'Verified',
    'EMF spike correlates with vehicle power loss. Movement pattern tracks with witness description of entity crossing road. Dashcam failure timestamp matches.',
    '{"sample_interval_ms": 200, "baseline_mg": 0.4, "peak_mg": 7.8, "phone_failures": 2, "dashcam_failure": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-030',
    'SIGHT-033',
    'Audio',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/audio/blue_orb_jazz.wav',
    'blue_orb_jazz.wav',
    23456789,
    'Tascam DR-40X',
    '2024-05-17 21:45:00',
    340,
    'Audio recording during Blue Lady orb manifestation. Background jazz music with additional harmonic resonance appearing during orb presence.',
    7.8,
    'Verified',
    'Spectral analysis shows additional harmonics not produced by band. Frequency matches historical 1930s recording equipment characteristics. Orb movement correlates with audio anomalies.',
    '{"sample_rate": "48000", "bit_depth": 24, "channels": 2, "anomaly_frequency_hz": 432, "harmonic_analysis": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-031',
    'SIGHT-042',
    'Thermal_Image',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/thermal/eastern_state_crawler.jpg',
    'eastern_state_crawler.jpg',
    2345678,
    'FLIR Scout TK',
    '2024-11-20 01:08:00',
    NULL,
    'Thermal image of Shadow Crawler in Eastern State Penitentiary cellblock. Cold mass visible on ceiling with descending tendrils toward floor.',
    8.9,
    'Verified',
    'Temperature differential shows -12°C entity against 5°C ambient. Mass shape consistent with previous Shadow Crawler thermal captures. Trail visible.',
    '{"resolution": "160x120", "entity_temp": -12, "ambient_temp": 5, "trail_visible": true, "motion_detected": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-032',
    'SIGHT-045',
    'Audio',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/audio/grey_lady_hymn.wav',
    'grey_lady_hymn.wav',
    34567890,
    'Church Recording System',
    '2024-12-24 00:05:00',
    234,
    'Chapel recording during Christmas Eve mass. Additional female voice audible joining hymn. Voice quality matches Victorian-era singing style.',
    8.4,
    'Verified',
    'Voice separation identifies source not among congregation. Singing style analysis consistent with 19th century formal vocal training. Multiple witnesses confirm hearing.',
    '{"sample_rate": "44100", "bit_depth": 16, "channels": 4, "voice_analysis": "victorian_style", "congregation_count": 6, "anomalous_voice": 1}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-033',
    'SIGHT-048',
    'Photograph',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/photos/green_man_autumn.jpg',
    'green_man_autumn.jpg',
    5678901,
    'Nikon D850',
    '2024-09-22 06:35:00',
    NULL,
    'Autumn equinox photograph of Green Man entity in oak grove. Figure composed of fallen leaves and bark. Eye contact through camera lens documented.',
    8.3,
    'Verified',
    'Image analysis confirms no digital manipulation. Figure construction shows impossible coherence for natural materials. Post-sighting found rare orchid at indicated location.',
    '{"iso": 800, "aperture": "f/4", "shutter_speed": "1/500s", "focal_length": "200mm", "raw_format": true, "orchid_found": true}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-034',
    'SIGHT-044',
    'Physical',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/physical/ouija_burn_pattern.jpg',
    'ouija_burn_pattern.jpg',
    876543,
    'Forensic Photography Kit',
    '2024-04-01 21:45:00',
    NULL,
    'Photograph of spontaneous burn pattern on Ouija board during Zozo contact. Board ignited without external heat source. Pattern shows Z-O-Z-O lettering.',
    9.0,
    'Verified',
    'Combustion analysis shows internal ignition. No accelerant detected. Burn pattern forms clear letter sequence. Material retained as evidence.',
    '{"ignition_source": "internal", "accelerant": false, "pattern": "ZOZO", "burn_temp_estimate_c": 400, "witness_count": 5}',
    CURRENT_TIMESTAMP()
),
(
    'EVID-035',
    'SIGHT-036',
    'Audio',
    '@GHOST_DETECTION.APP.EVIDENCE_STAGE/audio/bell_witch_battery_drain.wav',
    'bell_witch_battery_drain.wav',
    45678901,
    'Multiple Devices',
    '2024-11-15 02:15:00',
    892,
    'Audio compilation from multiple devices during Bell Witch investigation. Recording continues as batteries drained. EVP captured: "I am here." Equipment failure sounds audible.',
    9.1,
    'Verified',
    'Battery drain pattern shows simultaneous failure across 6 devices. EVP clearly audible despite power loss. Voice analysis matches historical Bell Witch recordings.',
    '{"devices_affected": 6, "drain_time_seconds": 45, "evp_clarity": "high", "voice_match": "historical_confirmed"}',
    CURRENT_TIMESTAMP()
);

-- Verify insert count and distribution
SELECT 
    EVIDENCE_TYPE,
    COUNT(*) AS EVIDENCE_COUNT,
    AVG(AUTHENTICITY_SCORE) AS AVG_AUTHENTICITY
FROM EVIDENCE
GROUP BY EVIDENCE_TYPE
ORDER BY EVIDENCE_COUNT DESC;

SELECT 
    ANALYSIS_STATUS,
    COUNT(*) AS COUNT
FROM EVIDENCE
GROUP BY ANALYSIS_STATUS;
